# Generated by Django 5.0.6 on 2024-08-25 14:15

from django.db import migrations

def load_sensors_data(apps, schema_editor):
    Sensor = apps.get_model('measurement', 'Sensor')
    Sensor.objects.create (
        name = "ESP32",
        description = "Датчик на кухне за холодильником"
        )
    Sensor.objects.create (
        name = "ESP33",
        description = "Датчик в коридоре"
        )

def load_measurement_data(apps, schema_editor):
    Measurement = apps.get_model('measurement', 'Measurement')
    Measurement.objects.create (
        sensor_id = 1,
        temperature = 22.3
        )
    Measurement.objects.create (
        sensor_id = 1,
        temperature = 20.3
        )
    Measurement.objects.create (
        sensor_id = 2,
        temperature = 26.3
        )
    Measurement.objects.create (
        sensor_id = 2,
        temperature = 18.3
        )

class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_sensors_data),
        migrations.RunPython(load_measurement_data),
    ]
